version: "3.7"

services:
  backend:
    build: ./easyin-backend-NodeJS/
    image: backend:v3
    container_name: backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./easyin-frontend-ReactJS/
    image: frontend:v1
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge